version: '3.4'

services:
    mailhog:
        # do not use in production!
        image: mailhog/mailhog:latest
        environment:
            - MH_STORAGE=maildir
        # volumes:
        #   - ./docker/mailhog/maildir:/maildir:rw,delegated
        ports:
            - "8025:8025" # UI
            - "1025:1025"
