sylius_resource:
    resources:
        bitbag_sylius_mail_template_plugin.email_template:
            driver: doctrine/orm
            classes:
                model: BitBag\SyliusMailTemplatePlugin\Entity\EmailTemplate
                interface: BitBag\SyliusMailTemplatePlugin\Entity\EmailTemplateInterface
                form: BitBag\SyliusMailTemplatePlugin\Form\Type\EmailTemplateType
                repository: BitBag\SyliusMailTemplatePlugin\Repository\EmailTemplateRepository
            translation:
                classes:
                    model: BitBag\SyliusMailTemplatePlugin\Entity\EmailTemplateTranslation
                    interface: BitBag\SyliusMailTemplatePlugin\Entity\EmailTemplateTranslationInterface
                    repository: BitBag\SyliusMailTemplatePlugin\Repository\EmailTemplateTranslationRepository
