sylius_grid:
    grids:
        bitbag_sylius_mail_template_plugin_email_template:
            driver:
                name: doctrine/orm
                options:
                    class: BitBag\SyliusMailTemplatePlugin\Entity\EmailTemplate
            fields:
                name:
                    type: string
                    label: bitbag_sylius_mail_template_plugin.ui.template_name
                subject:
                    type: string
                    label: bitbag_sylius_mail_template_plugin.ui.template_subject
            filters:
                name:
                    type: string
                    label: sylius.ui.name
                    options:
                        fields: [ translations.name ]
                subject:
                    type: string
                    label: sylius.ui.subject
                    options:
                        fields: [ translations.subject ]
                content:
                    type: string
                    label: sylius.ui.content
                    options:
                        fields: [ translations.content ]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
