bitbag_sylius_mail_template_plugin_admin_email_template:
    resource: |
        alias: bitbag_sylius_mail_template_plugin.email_template
        section: admin
        path: /mail-template
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        permission: true
        grid: bitbag_sylius_mail_template_plugin_email_template
        vars:
            all:
                subheader: bitbag_sylius_mail_template_plugin.ui.description
                templates:
                    form: "@BitBagSyliusMailTemplatePlugin/Admin/EmailTemplate/Crud/_form.html.twig"
            index:
                icon: 'envelope'
    type: sylius.resource
